language: cpp
dist: trusty
sudo: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CXX=g++-7"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-5.0
            - libstdc++-7-dev
      env:
        - MATRIX_EVAL="CXX=clang++-5.0"

    - os: osx
      osx_image: xcode8.3
      env:
        - MATRIX_EVAL="CXX=clang++-5.0"

before_install:
  - eval "${MATRIX_EVAL}"

notifications:
  email:
    on_success: never
    on_failure: always

script:
  - mkdir build && cd build
  - cmake .. && make VERBOSE=1
  - CTEST_OUTPUT_ON_FAILURE=1 make test
